title: Optivem Repository (C#)
description: Interfaces for Generic Repository and Unit of Work
google_analytics: UA-63306472-4
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions