title: Optivem Enterprise Framework (Java)
description: Framework for enterprise applications in Java
google_analytics: UA-63306472-4
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions