title: Optivem .NET Commons Persistence
description: Interfaces for generic repository and generic unit of work patterns
google_analytics: UA-63306472-4
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions